// RC-scoreboard-gold-main/client/src/components/ui/button.tsx
import * as React from 'react';
import { Slot } from '@radix-ui/react-slot';
import { cva, type VariantProps } from 'class-variance-authority';

import { cn } from '@/lib/utils';

const buttonVariants = cva(
	'inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0',
	{
		variants: {
			variant: {
				default: 'bg-primary text-primary-foreground hover:bg-primary/90',
				destructive: 'bg-destructive text-destructive-foreground hover:bg-destructive/90',
				outline: 'border border-input bg-background hover:bg-accent hover:text-accent-foreground',
				secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80',
				ghost: 'hover:bg-accent hover:text-accent-foreground',
				link: 'text-primary underline-offset-4 hover:underline'
			},
			size: {
				default: 'h-10 px-4 py-2',
				sm: 'h-9 rounded-md px-3',
				lg: 'h-11 rounded-md px-8',
				icon: 'h-10 w-10'
			}
		},
		defaultVariants: {
			variant: 'default',
			size: 'default'
		}
	}
);

export interface ButtonProps
	extends React.ButtonHTMLAttributes<HTMLButtonElement>,
		VariantProps<typeof buttonVariants> {
	asChild?: boolean;
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
	({ className, variant, size, asChild = false, ...props }, ref) => {
		const Comp = asChild ? Slot : 'button';
		return (
			<Comp className={cn(buttonVariants({ variant, size, className }))} ref={ref} {...props} />
		);
	}
);
Button.displayName = 'Button';

export { Button, buttonVariants };

// src/lib/components/Button.svelte
<script lang="ts">
	export let variant = 'primary'; // primary, secondary, outline, danger
	export let size = 'md'; // sm, md, lg
	export let type = 'button';
	export let disabled = false;
	export let fullWidth = false;
	export let href = '';

	// Compute classes based on props
	$: classes = [
		// Base styles
		'rounded-md font-medium transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2',

		// Size variants
		size === 'sm' ? 'text-sm px-3 py-1.5' : size === 'lg' ? 'text-lg px-6 py-3' : 'px-4 py-2', // Default (md)

		// Color variants
		variant === 'primary'
			? 'bg-blue-800 hover:bg-blue-900 text-white focus:ring-blue-500'
			: variant === 'secondary'
				? 'bg-blue-600 hover:bg-blue-700 text-white focus:ring-blue-500'
				: variant === 'outline'
					? 'border border-blue-600 text-blue-600 hover:bg-blue-50 focus:ring-blue-500'
					: variant === 'danger'
						? 'bg-red-600 hover:bg-red-700 text-white focus:ring-red-500'
						: 'bg-gray-200 hover:bg-gray-300 text-gray-800 focus:ring-gray-500', // Default/text

		// Width
		fullWidth ? 'w-full' : '',

		// Disabled
		disabled ? 'opacity-50 cursor-not-allowed' : ''
	]
		.filter(Boolean)
		.join(' ');
</script>

{#if href}
	<a {href} class={classes} class:disabled on:click>
		<slot />
	</a>
{:else}
	<button {type} class={classes} {disabled} on:click>
		<slot />
	</button>
{/if}
